// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI5MbmyNDq-nqt9FAs3x6wP80BQhb-idQ',
    appId: '1:473476526286:web:50fa5197fdc86a3a0fa09f',
    messagingSenderId: '473476526286',
    projectId: 'paytrans-e3920',
    authDomain: 'paytrans-e3920.firebaseapp.com',
    databaseURL: 'https://paytrans-e3920-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'paytrans-e3920.appspot.com',
    measurementId: 'G-J5YSXZLM9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxoViDYxSh8X3lhXfDWdn9CC6_MiTus5A',
    appId: '1:473476526286:android:ef637f9e23e70c240fa09f',
    messagingSenderId: '473476526286',
    projectId: 'paytrans-e3920',
    databaseURL: 'https://paytrans-e3920-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'paytrans-e3920.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyDmrmXzcKHLQUH6PJnhWo0TOGofyJPS8',
    appId: '1:473476526286:ios:fdd40257ea64d5770fa09f',
    messagingSenderId: '473476526286',
    projectId: 'paytrans-e3920',
    databaseURL: 'https://paytrans-e3920-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'paytrans-e3920.appspot.com',
    androidClientId: '473476526286-dafb9eaupd8omrle0auqe7o6gfn195kq.apps.googleusercontent.com',
    iosBundleId: 'com.example.paytrans',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyDmrmXzcKHLQUH6PJnhWo0TOGofyJPS8',
    appId: '1:473476526286:ios:fdd40257ea64d5770fa09f',
    messagingSenderId: '473476526286',
    projectId: 'paytrans-e3920',
    databaseURL: 'https://paytrans-e3920-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'paytrans-e3920.appspot.com',
    androidClientId: '473476526286-dafb9eaupd8omrle0auqe7o6gfn195kq.apps.googleusercontent.com',
    iosBundleId: 'com.example.paytrans',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI5MbmyNDq-nqt9FAs3x6wP80BQhb-idQ',
    appId: '1:473476526286:web:b94e107e43754ec40fa09f',
    messagingSenderId: '473476526286',
    projectId: 'paytrans-e3920',
    authDomain: 'paytrans-e3920.firebaseapp.com',
    databaseURL: 'https://paytrans-e3920-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'paytrans-e3920.appspot.com',
    measurementId: 'G-Y4608E4LP4',
  );
}
